version: 2.1
workflows:
    lint_and_test:
        jobs:
            - build
            - lint
            - core-test:
                requires:
                  - build
            - core-cli-test:
                requires:
                  - build
            - circuits-test:
                requires:
                  - build
            - contracts-test:
                requires:
                  - build
            - crypto-test:
                requires:
                  - build
jobs:
    build:
        docker:
            - image: node:14
        steps:
            - checkout
            - run:
                  name: Install Yarn
                  command: curl -o- -L https://yarnpkg.com/install.sh | bash
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: yarn build
            - persist_to_workspace:
                root: ~/
                paths: project
    lint:
        docker:
            - image: node:14
        steps:
            - checkout
            - run:
                  name: Install Yarn
                  command: curl -o- -L https://yarnpkg.com/install.sh | bash
            - run:
                  name: Install
                  command: yarn
            - run:
                  name: Lint
                  command: yarn lint --check
    core-test:
        docker:
            - image: node:14
        steps:
            - attach_workspace:
                - at: ~/
            - run:
                  name: Test
                  command: yarn core test
    core-cli-test:
        docker:
            - image: node:14
        steps:
            - attach_workspace:
                - at: ~/
            - run:
                  name: Test
                  command: yarn core test-cli
    circuits-test:
        docker:
            - image: node:14
        steps:
            - attach_workspace:
                - at: ~/
            - run:
                  name: Test
                  command: yarn circuits test
    contracts-test:
        docker:
            - image: node:14
        steps:
            - attach_workspace:
                - at: ~/
            - run:
                  name: Test
                  command: yarn contracts test
    crypto-test:
        docker:
            - image: node:14
        steps:
            - attach_workspace:
                - at: ~/
            - run:
                  name: Test
                  command: yarn crypto test
