version: 2.1
workflows:
    test_app:
        jobs:
            - build
            - lint
            - test:
              requires:
                - build

jobs:
    build:
        docker:
            - image: node:14
        steps:
            - checkout
            - run:
                  name: Install Yarn
                  command: curl -o- -L https://yarnpkg.com/install.sh | bash
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: yarn build
    lint:
        docker:
            - image: node:14
        steps:
            - checkout
            - run:
                  name: Install Yarn
                  command: curl -o- -L https://yarnpkg.com/install.sh | bash
            - run:
                  name: Install
                  command: yarn
            - run:
                  name: Lint
                  command: yarn lint --check
    test:
        docker:
            - image: node:14
        steps:
            - run:
                  name: Test
                  command: cd packages/core && yarn test
